//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SciencesStudies.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstituteDbEntities : DbContext
    {
        public InstituteDbEntities()
            : base("name=InstituteDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academicians> Academicians { get; set; }
        public virtual DbSet<CollegeStudents> CollegeStudents { get; set; }
        public virtual DbSet<EnglishBooks> EnglishBooks { get; set; }
        public virtual DbSet<ForeignMembers> ForeignMembers { get; set; }
        public virtual DbSet<GeneralBooks> GeneralBooks { get; set; }
        public virtual DbSet<GeneralMembers> GeneralMembers { get; set; }
        public virtual DbSet<Journals> Journals { get; set; }
        public virtual DbSet<LiteratureBooks> LiteratureBooks { get; set; }
        public virtual DbSet<MathematicalBooks> MathematicalBooks { get; set; }
        public virtual DbSet<Newspapers> Newspapers { get; set; }
        public virtual DbSet<OrderList> OrderList { get; set; }
        public virtual DbSet<Researchers> Researchers { get; set; }
        public virtual DbSet<SocialBooks> SocialBooks { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
