//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SciencesStudies.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newspapers
    {
        public int Id { get; set; }
        public string NewspapersName { get; set; }
        public string LanguageOfIt { get; set; }
        public string Contry { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
