//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SciencesStudies.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialBooks
    {
        public int Id { get; set; }
        public string BookName { get; set; }
        public string LanguageOfIt { get; set; }
        public string KindOfBook { get; set; }
        public string AuthorName { get; set; }
        public Nullable<int> Price { get; set; }
        public string Branch { get; set; }
    }
}
